---
deployment: 
  tasks:
    - export DEPLOYPATH=/home/cyiuhimc/public_html/templates
    - /bin/cp -r ../images $DEPLOYPATH
    - /bin/cp -r . $DEPLOYPATH
    - /bin/cp -r ../attachments $DEPLOYPATH