---
deployment: 
  tasks:
    - export DEPLOYPATH=/home/cyiuhimc/public_html/
    - /bin/cp -r images $DEPLOYPATH
    - /bin/cp *.html $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp -r attachments $DEPLOYPATH